spring.application.name=department-service

#From here further credentials added in git repo and yes the name of git file must be application name.properties

#tell this from where you have to find further settings:
spring.config.import=optional:configserver:http://localhost:8888
