spring.application.name=02-jpa

spring.datasource.url=jdbc:postgresql://localhost:5432/JPA_Demo
spring.datasource.username=postgres
spring.datasource.password=Temp@123456


# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Logging
logging.level.org.hibernate.springframework=info
logging.level.root=info
logging.file.path=.


#mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dushyant.testspring@gmail.com
spring.mail.password=qyraaaanzfhjqghc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000


#Twillio for messeging

twilio.account.sid=AC3a7c7aca7d283ff39ab5aa0caade4b88
twilio.auth.token=64ed2015aa37120e424c4ac76457819d
twilio.phone.number=+17372508034