spring.application.name=employee-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/microService_employee
spring.datasource.username=postgres
spring.datasource.password=Temp@123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


eureka.client.serivce-url.defaultZone=http://localhost:8761/eureka
