spring.application.name=security_demo

spring.datasource.url=jdbc:postgresql://localhost:5432/security_demo
spring.datasource.username=postgres
spring.datasource.password=Temp@123456

server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT configuration (required by JwtTokenProvider)
app.jwt.secret=FVyTWBlPExGYGt6QR5V8iMBNSP7jATTANIep6rNlprE
# expiration in milliseconds (e.g., 86400000 = 1 day)
app.jwt.expiration=86400000

#Following are for redis dependency
spring.data.redis.host=localhost
spring.data.redis.port=6379